[package]
name = "cafecoder-rs"
version = "0.1.0"
authors = ["earlgray <earlgray283@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.4.2", features = [ "runtime-async-std-native-tls", "mysql", "macros", "chrono" ] }
async-std = { version = "1.8.0", features = [ "attributes" ] }
dotenv = "0.15.0"
chrono = "0.4"
bollard = "0.9"
rand = "0.8.0"
tokio = { version = "0.2", features = [ "full" ] }
hyper = "0.14"