version: "3"

services:

  db:
    build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=earlgray
      - MYSQL_PASSWORD=329issocute

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080